language: generic
sudo: required
servises:
  - docker

before_install:
  - docker build -t hiranokuosaka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hiranokuosaka/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-3'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-3-106351276515'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
