language: generic
sudo: required
servises:
  - docker

before_install:
  - docker build -t hiranokuosaka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hiranokuosaka/docker-react npm run test
